"""Deterministic, stateful security-findings service (CKS coverage).

Provides findings across the four CKS layers — application, container,
node-cloud, kubernetes-cluster — seeded from a static, deterministic scan.
Every finding carries the full per-finding structure (Issue, Severity,
Evidence, Affected Resource, Root Cause, Recommended Solution, Auto/Approval
Required, Remediation Status, Verification Status) and is labelled SIMULATED
when generated by this in-process store rather than a live scanner.

Security invariant (unchanged): the LLM is advisory only. Diagnoses are
produced by the mock/configured LLM, but remediation decisions come from the
authoritative policy engine, and execution only ever mutates the in-process
simulated cluster (or the allow-listed live demo namespace).
"""

from __future__ import annotations

import threading
from datetime import timedelta
from typing import Any, Optional

from backend.models.incident import (
    EvidenceItem,
    FindingStatus,
    PolicyDecisionType,
    SecurityFinding,
    SecurityFindingRequest,
    SecurityLayer,
    Severity,
    TimelineEvent,
    VerificationStatus,
)
from backend.policy.engine import get_policy_engine
from backend.services import chrono, kube, store

_lock = threading.RLock()

_findings: dict[str, SecurityFinding] = {}
_counter = 0
_seeded = False


def reset_findings() -> None:
    global _findings, _counter, _seeded
    with _lock:
        _findings = {}
        _counter = 0
        _seeded = False


def next_finding_id() -> str:
    global _counter
    with _lock:
        _counter += 1
        return f"sec-{_counter:04d}"


# ---------------------------------------------------------------------------
# Seed data — deterministic simulated CKS findings (labelled SIMULATED)
# ---------------------------------------------------------------------------


def _seed_specs() -> list[dict[str, Any]]:
    """Static, deterministic scan results for the demo cluster."""
    now = chrono.now()
    ns = "ai-observability-demo"
    return [
        {
            "title": "demo-app pod crash-looping (missing config)",
            "issue": "demo-app container restarts repeatedly because /etc/demo/config.yaml is missing; the deployment has no healthcheck gate so replicas report available=0.",
            "severity": Severity.MEDIUM,
            "layer": SecurityLayer.APPLICATION,
            "domain": "ConfigDrift",
            "affected_resource": "Deployment/demo-app",
            "root_cause": "ConfigMap not mounted + container entrypoint exits 1 when the file is absent.",
            "recommended_solution": "Restart the deployment after ensuring the ConfigMap is created and mounted.",
            "recommended_action": "restart_deployment",
            "action_params": {"deployment": "demo-app", "namespace": ns},
            "evidence": ["kube_events: BackOff restarting failed container (count=7)", "pod logs: ERROR config file not found", "deployment status: available=0"],
        },
        {
            "title": "privileged container in test-pod",
            "issue": "test-pod runs its container with privileged=true, defeating namespace isolation and granting most host capabilities.",
            "severity": Severity.HIGH,
            "layer": SecurityLayer.CONTAINER,
            "domain": "Privileged",
            "affected_resource": "Pod/test-pod",
            "root_cause": "PodSecurityContext.privileged set in the demo manifest (simulated control-plane risk hole).",
            "recommended_solution": "Regenerate the pod spec with privileged=false and apply an AppArmor profile.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "drop-privileged", "target": "test-pod", "namespace": ns},
            "evidence": ["falco: Terminal shell in container (CRITICAL)", "audit: pods/exec on test-pod", "kubelet: admitted with privileged"],
        },
        {
            "title": "AppArmor profile not applied on crash-demo",
            "issue": "crash-demo containers run without an AppArmor containment profile, so a compromised process gets broader host filesystem access.",
            "severity": Severity.MEDIUM,
            "layer": SecurityLayer.CONTAINER,
            "domain": "AppArmor",
            "affected_resource": "Pod/crash-demo",
            "root_cause": "container.apparmorProfile not set; runtime annotation absent.",
            "recommended_solution": "Include the demo AppArmor profile via apply_security_config(config=enable-apparmor).",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "enable-apparmor", "target": "crash-demo", "namespace": ns},
            "evidence": ["kubelet: container.apparmor.security.beta annotation missing", "admission audit of Pod/crash-demo"],
        },
        {
            "title": "seccomp runs in unconfined/unrestricted mode on memory-demo",
            "issue": "memory-demo containers are not running under the RuntimeDefault seccomp profile; the default policy does not confine syscalls.",
            "severity": Severity.MEDIUM,
            "layer": SecurityLayer.CONTAINER,
            "domain": "Seccomp",
            "affected_resource": "Deployment/memory-demo",
            "root_cause": "spec.securityContext.seccompProfile unset.",
            "recommended_solution": "Drop to seccompProfile=RuntimeDefault so the runtime default filter is enforced.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "enable-seccomp", "target": "memory-demo", "namespace": ns},
            "evidence": ["pod spec: seccompProfile missing", "runtime default profile NOT applied"],
        },
        {
            "title": "no default-deny NetworkPolicy in the demo namespace",
            "issue": "Pods can reach each other on all ports; any compromised pod gets unrestricted east-west network access.",
            "severity": Severity.HIGH,
            "layer": SecurityLayer.KUBERNETES_CLUSTER,
            "domain": "NetworkPolicy",
            "affected_resource": "Namespace/ai-observability-demo",
            "root_cause": "No NetworkPolicy objects in the namespace.",
            "recommended_solution": "Apply a default-deny ingress/egress NetworkPolicy, then allow the demo-app/Cert flows explicitly.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "default-deny-network-policy", "target": "ai-observability-demo", "namespace": ns},
            "evidence": ["netpol list empty", "CNI plugin reports no policies for namespace"],
        },
        {
            "title": "clustered-binding ci-bot-cluster-admin grants cluster-admin",
            "issue": "A CI ServiceAccount received cluster-admin, allowing full control-plane modification; the binding was created 18 minutes ago.",
            "severity": Severity.CRITICAL,
            "layer": SecurityLayer.KUBERNETES_CLUSTER,
            "domain": "RBAC",
            "affected_resource": "ClusterRoleBinding/ci-bot-cluster-admin",
            "root_cause": "Over-privileged role binding (simulated) — least-privilege rule violated.",
            "recommended_solution": "Roll back the binding (delete) and issue a least-privilege ClusterRole instead.",
            "recommended_action": "rollback_rbac",
            "action_params": {"binding_name": "ci-bot-cluster-admin"},
            "evidence": ["kubernetes-audit: create clusterrolebindings (verb=create)", "kube-state: subject ci-bot has cluster-admin"],
        },
        {
            "title": "control-plane kubelet metrics exposed anonymously",
            "issue": "The control-plane kubelet serves metrics with anonymous-auth still enabled, letting unauthenticated users enumerate workloads.",
            "severity": Severity.HIGH,
            "layer": SecurityLayer.NODE_CLOUD,
            "domain": "Kubelet",
            "affected_resource": "Node/demo-control-plane",
            "root_cause": "system:anonymous granted access on /metrics (simulated misconfiguration).",
            "recommended_solution": "Disable anonymous metrics access and switch kubelet authorizer to Webhook.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "lockdown-kubelet", "target": "demo-control-plane", "namespace": ns},
            "evidence": ["node probe: 401 allowed for anonymous /metrics", "kubelet config: authentication webhook not set"],
        },
        {
            "title": "Trivy reports known CVEs in nginx:1.25 for demo-app",
            "issue": "Image scanning (Trivy) flags several published CVEs in the nginx:1.25 image used by demo-app; the mutable tag prevents a clean rollback.",
            "severity": Severity.HIGH,
            "layer": SecurityLayer.CONTAINER,
            "domain": "SCA",
            "affected_resource": "Deployment/demo-app (image nginx:1.25)",
            "root_cause": "outdated base image + mutable tag → known-exploitable container image.",
            "recommended_solution": "Pin the patched image (tidy-image) and roll it out; approval required.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "tidy-image", "target": "demo-app", "namespace": ns},
            "evidence": ["trivy scan: 3 HIGH / 8 MEDIUM CVEs in nginx:1.25", "image digest mutable (nginx:1.25 → nginx:1.25-alpine)"],
        },
        {
            "title": "database password passed via environment variable",
            "issue": "demo-app receives its database password through a plaintext env var instead of a mounted Secret; the value is visible in pod spec and audit.",
            "severity": Severity.HIGH,
            "layer": SecurityLayer.CONTAINER,
            "domain": "Secrets",
            "affected_resource": "Deployment/demo-app (env DB_PASSWORD)",
            "root_cause": "config values embedded in the manifest instead of a Secret object.",
            "recommended_solution": "Move the credential into a Secret and reference it via envFrom; approval required.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "use-secret", "target": "demo-app", "namespace": ns},
            "evidence": ["pod spec: env DB_PASSWORD=**** (plaintext)", "audit: GET secrets demo-app/db-password 403"],
        },
        {
            "title": "hostNetwork + privileged admission on injected lab pod",
            "issue": "lab-pod was admitted with hostNetwork=true and privileged=true, exposing the host network namespace and its full capabilities.",
            "severity": Severity.CRITICAL,
            "layer": SecurityLayer.CONTAINER,
            "domain": "PodSecurity",
            "affected_resource": "Pod/lab-pod",
            "root_cause": "PodSecurity admission allowed hostNetwork/privileged on a demo workload.",
            "recommended_solution": "Deny hostNetwork/privileged and regenerate the pod spec; approval required.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "disallow-host-network", "target": "lab-pod", "namespace": ns},
            "evidence": ["kubelet: admitted pod with hostNetwork=true", "falco: Unexpected network connection in container (CRITICAL)"],
        },
        {
            "title": "automountServiceAccountToken left enabled on ci-bot",
            "issue": "ci-bot pods auto-mount the default ServiceAccount token even though no in-cluster API access is needed; a compromised pod could call the API server.",
            "severity": Severity.MEDIUM,
            "layer": SecurityLayer.KUBERNETES_CLUSTER,
            "domain": "ServiceAccount",
            "affected_resource": "ServiceAccount/ci-bot (namespace ci)",
            "root_cause": "automountServiceAccountToken not set to false; broad api access by default.",
            "recommended_solution": "Disable token auto-mounting and bind a least-privilege ServiceAccount; approval required.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "disable-auto-mount-token", "target": "ci-bot", "namespace": ns},
            "evidence": ["kube-state: token mounted on ci-bot pods", "audit: system:serviceaccount:ci:ci-bot GET /apis"],
        },
        {
            "title": "capability audit: NET_RAW + CHOWN not dropped on demo-app",
            "issue": "demo-app containers run with the default capability set (NET_RAW, CHOWN, …) instead of dropping all capabilities and re-adding only what is needed.",
            "severity": Severity.MEDIUM,
            "layer": SecurityLayer.CONTAINER,
            "domain": "Capabilities",
            "affected_resource": "Deployment/demo-app",
            "root_cause": "securityContext.capabilities.drop not set in the manifest.",
            "recommended_solution": "Drop all capabilities via drop-capabilities and re-add required ones; approval required.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "drop-capabilities", "target": "demo-app", "namespace": ns},
            "evidence": ["pod spec: capabilities NOT dropped", "runtime: default cap_net_raw + cap_chown present"],
        },
        {
            "title": "ImagePullPolicy not Always on cert-demo",
            "issue": "cert-demo runs with ImagePullPolicy=IfNotPresent, so a node can keep serving an old, vulnerable image after it is pulled once.",
            "severity": Severity.MEDIUM,
            "layer": SecurityLayer.CONTAINER,
            "domain": "ImagePolicy",
            "affected_resource": "Deployment/cert-demo",
            "root_cause": "imagePullPolicy omitted in the workload manifest.",
            "recommended_solution": "Enforce ImagePullPolicy=Always for mutable tags; approval required.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "set-image-pull-policy", "target": "cert-demo", "namespace": ns},
            "evidence": ["pod spec: imagePullPolicy=IfNotPresent", "kubelet: reused local image for cert-demo starting"],
        },
        {
            "title": "worker kubelet runs without --protect-kernel-defaults",
            "issue": "demo-worker-1 kubelet does not enforce --protect-kernel-defaults, so kernel defaults (sysctl) can be changed by containers with CAP_SYS_ADMIN.",
            "severity": Severity.MEDIUM,
            "layer": SecurityLayer.NODE_CLOUD,
            "domain": "Kubelet",
            "affected_resource": "Node/demo-worker-1",
            "root_cause": "kubelet flags missing for kernel-default protection / seccomp at node level.",
            "recommended_solution": "Enable protect-kernel-defaults and a node-level seccomp profile; approval required.",
            "recommended_action": "apply_security_config",
            "action_params": {"config": "lockdown-kubelet", "target": "demo-worker-1", "namespace": ns},
            "evidence": ["node probe: protect-kernel-defaults false", "kubelet config: sysctls not restricted"],
        },
    ]


def _to_evidence(clues: list[str]) -> list[EvidenceItem]:
    source = "simulated-scan"
    return [
        EvidenceItem(category="security-scan", source=source, summary=clue, data={"simulated": True})
        for clue in clues
    ]


def _seed() -> None:
    global _seeded
    with _lock:
        if _seeded:
            return
        for spec in _seed_specs():
            finding = _hydrate(spec, source="simulated-scan")
            _run_pipeline_body(finding)
            _findings[finding.finding_id] = finding
        _seeded = True


# ---------------------------------------------------------------------------
# pipeline — detect -> (advisory LLM) diagnose -> policy -> remediate -> verify
# ---------------------------------------------------------------------------


def _hydrate(spec: dict[str, Any], source: str) -> SecurityFinding:
    now = chrono.now()
    fid = next_finding_id()
    decision = PolicyDecisionType.NO_ACTION
    status = FindingStatus.OPEN
    remediation_status = "not_started"
    verification_status = VerificationStatus.PENDING
    params = dict(spec.get("action_params") or {})

    f = SecurityFinding(
        finding_id=fid,
        title=spec["title"],
        issue=spec["issue"],
        severity=Severity(spec.get("severity", Severity.MEDIUM)),
        layer=SecurityLayer(spec.get("layer", SecurityLayer.APPLICATION)),
        status=status,
        domain=spec.get("domain", ""),
        evidence=_to_evidence(spec.get("evidence") or []),
        affected_resource=spec.get("affected_resource", ""),
        root_cause=spec.get("root_cause", ""),
        recommended_solution=spec.get("recommended_solution", ""),
        recommended_action=spec.get("recommended_action", ""),
        action_params=params,
        decision=decision,
        approval_required=False,
        remediation_status=remediation_status,
        verification_status=verification_status,
        simulated=True,
        source=source,
        detected_at=now,
        created_at=now,
        updated_at=now,
    )
    f.add_to_timeline("created", f"finding injected from {source}")
    return f


def _diagnose(finding: SecurityFinding) -> str:
    """Advisory diagnosis.

    Uses the configured LLM (mock = offline deterministic) purely for prose;
    the returned text is a *proposal* — the policy engine remains authoritative.
    """
    from backend.services.llm import get_llm

    try:
        text = get_llm().diagnose_finding(finding)
        if text:
            return str(text)
    except Exception:  # noqa: BLE001 — diagnosis must never block the finding
        pass
    return (
        f"{finding.title}: {finding.root_cause} — recommend {finding.recommended_solution} "
        f"(policy engine decides the actual remediation decision)."
    )


def _apply_safe_config(config: str, target: str, namespace: str) -> dict[str, Any]:
    """Simulated, fully in-process security config change (no live cluster)."""
    return kube.get_kube().apply_security_config(config, target, namespace)


def _remediate_body(finding: SecurityFinding) -> dict[str, Any]:
    params = dict(finding.action_params)
    action = finding.recommended_action
    if action == "restart_deployment":
        return kube.get_kube().restart_deployment(params.get("deployment", ""), params.get("namespace", "ai-observability-demo"))
    if action == "scale_deployment":
        return kube.get_kube().scale_deployment(params.get("deployment", ""), params.get("namespace", "ai-observability-demo"), int(params.get("desired_replicas", 2)))
    if action == "rollback_rbac":
        return kube.get_kube().rollback_rbac(params.get("binding_name", ""))
    if action == "renew_certificate":
        return kube.get_kube().renew_certificate(params.get("namespace", "ai-observability-demo"), "cert-demo-tls", "cert-demo.ai-observability-demo.svc")
    if action == "apply_security_config":
        return _apply_safe_config(params.get("config", ""), params.get("target", ""), params.get("namespace", "ai-observability-demo"))
    return {"action": action, "result": "no-op", "detail": "no safe remediation mapped for this action"}


def _verify_body(finding: SecurityFinding) -> list[dict[str, Any]]:
    """Deterministic verification checks for the finding's remediation."""
    params = dict(finding.action_params)
    action = finding.recommended_action
    ns = params.get("namespace", "ai-observability-demo")
    checks: list[dict[str, Any]] = []
    try:
        if action == "restart_deployment":
            dep = kube.get_kube().get_deployment(params.get("deployment", ""), ns)
            checks.append({"name": "available", "passed": dep.get("available", 0) == dep.get("replicas", 0) and dep.get("available", 0) > 0, "actual": dep.get("available"), "detail": "deployment available"})
        elif action == "scale_deployment":
            dep = kube.get_kube().get_deployment(params.get("deployment", ""), ns)
            checks.append({"name": "replicas", "passed": dep.get("replicas", 0) == int(params.get("desired_replicas", 0)), "actual": dep.get("replicas"), "detail": "deployment at desired replica count"})
        elif action == "rollback_rbac":
            gone = not any(b.get("name") == params.get("binding_name") for b in kube.get_kube().get_rbac())
            checks.append({"name": "binding_removed", "passed": gone, "detail": "suspicious binding removed"})
        elif action == "apply_security_config":
            ok = kube.get_kube().security_config_applied(params.get("config", ""), params.get("target", ""))
            checks.append({"name": f"config:{params.get('config')}", "passed": ok, "detail": "security config applied to target"})
        else:
            checks.append({"name": "remediated", "passed": True, "detail": "no-op — nothing to verify"})
    except Exception as exc:  # noqa: BLE001
        checks.append({"name": "verify_error", "passed": False, "detail": str(exc)})
    return checks


def _run_pipeline_body(finding: SecurityFinding) -> None:
    """Safe pipeline: detect -> diagnose (advisory LLM) -> policy -> auto/approval."""
    finding.status = FindingStatus.DETECTED
    finding.add_to_timeline("detected", f"detected via {finding.source}")

    diag = _diagnose(finding)
    finding.add_to_timeline("diagnosed", diag)

    decision = get_policy_engine().evaluate_finding(finding)
    finding.decision = decision.decision
    finding.add_to_timeline("policy_checked", f"{decision.rule_id}: {decision.reason}")

    if decision.decision == PolicyDecisionType.NO_ACTION or decision.decision == PolicyDecisionType.BLOCKED:
        finding.status = FindingStatus.OPEN if decision.decision == PolicyDecisionType.NO_ACTION else FindingStatus.OPEN
        finding.add_to_timeline("no_action", decision.reason)
        return

    finding.approval_required = decision.decision == PolicyDecisionType.APPROVAL_REQUIRED
    if decision.decision == PolicyDecisionType.AUTO:
        finding.status = FindingStatus.REMEDIATING
        finding.remediation_status = "in_progress"
        finding.add_to_timeline("remediating", f"auto remediation via {finding.recommended_action}")
        _finish_remediation(finding)
    else:
        finding.status = FindingStatus.AWAITING_APPROVAL
        finding.remediation_status = "not_started"
        finding.add_to_timeline("waiting_approval", "human approval required before remediation")


def _finish_remediation(finding: SecurityFinding) -> None:
    finding.status = FindingStatus.REMEDIATING
    finding.remediation_status = "in_progress"
    try:
        result = _remediate_body(finding)
        finding.add_to_timeline("remediated", f"{finding.recommended_action}: {result.get('result', result)}")
        finding.remediation_status = "complete"
        checks = _verify_body(finding)
        finding.verification_checks = checks
        passed = bool(checks) and all(c.get("passed") for c in checks)
        finding.verification_status = VerificationStatus.PASSED if passed else VerificationStatus.FAILED
        finding.status = FindingStatus.REMEDIATED if passed else FindingStatus.VERIFICATION_FAILED
        finding.add_to_timeline(
            "verified",
            f"verification {'PASSED' if passed else 'FAILED'}: {[c.get('name') for c in checks]}",
        )
    except Exception as exc:  # noqa: BLE001
        finding.add_to_timeline("remediation_error", str(exc))
        finding.status = FindingStatus.OPEN
        finding.remediation_status = "failed"
    finding.touch()


# ---------------------------------------------------------------------------
# Store API
# ---------------------------------------------------------------------------


def get_store():
    _seed()
    return _findings


def list_findings(
    layer: Optional[str] = None,
    status: Optional[str] = None,
    severity: Optional[str] = None,
    domain: Optional[str] = None,
    simulated_only: bool = True,
) -> list[SecurityFinding]:
    findings = sorted(get_store().values(), key=lambda f: f.detected_at, reverse=True)
    if layer:
        findings = [f for f in findings if f.layer.value == layer]
    if status:
        findings = [f for f in findings if f.status.value == status.upper()]
    if severity:
        findings = [f for f in findings if f.severity.value == severity]
    if domain:
        findings = [f for f in findings if f.domain.lower() == domain.lower()]
    if simulated_only:
        findings = [f for f in findings if f.simulated]
    return findings


def get_finding(finding_id: str) -> Optional[SecurityFinding]:
    return get_store().get(finding_id)


def stats() -> dict[str, Any]:
    findings = list(get_store().values())
    layers: dict[str, dict[str, Any]] = {}
    for layer in SecurityLayer:
        layers[layer.value] = {"total": 0, **{s.value: 0 for s in Severity}, "remediated": 0, "waiting": 0}
    by_severity = {s.value: 0 for s in Severity}
    by_status = {st.value: 0 for st in FindingStatus}
    for f in findings:
        layers[f.layer.value]["total"] += 1
        layers[f.layer.value][f.severity.value] += 1
        if f.verification_status == VerificationStatus.PASSED:
            layers[f.layer.value]["remediated"] += 1
        if f.status == FindingStatus.AWAITING_APPROVAL:
            layers[f.layer.value]["waiting"] += 1
        by_severity[f.severity.value] += 1
        by_status[f.status.value] += 1
    return {
        "total": len(findings),
        "simulated": len([f for f in findings if f.simulated]),
        "by_layer": layers,
        "by_severity": by_severity,
        "by_status": by_status,
        "domains": sorted({f.domain for f in findings if f.domain}),
    }


# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------


def create_finding(req: SecurityFindingRequest, source: str = "test-lab") -> SecurityFinding:
    """Inject a new finding (Security Test Lab) and run the safe pipeline."""
    finding = _hydrate(
        {
            "title": req.title,
            "issue": req.issue,
            "severity": req.severity,
            "layer": req.layer,
            "domain": req.domain,
            "affected_resource": req.affected_resource,
            "root_cause": req.root_cause,
            "recommended_solution": req.recommended_solution,
            "recommended_action": req.recommended_action,
            "action_params": req.action_params,
            "evidence": [req.issue],
        },
        source=source,
    )
    with _lock:
        _run_pipeline_body(finding)
        _findings[finding.finding_id] = finding
    return finding


def decide_finding(finding_id: str, decision: str, approved_by: str = "webui-user", reason: str = "") -> SecurityFinding:
    finding = get_finding(finding_id)
    if finding is None:
        raise KeyError(finding_id)
    if finding.status != FindingStatus.AWAITING_APPROVAL:
        raise ValueError(f"finding {finding_id} is not waiting for approval (status={finding.status.value})")
    if decision == "reject":
        finding.status = FindingStatus.OPEN
        finding.remediation_status = "not_started"
        finding.add_to_timeline("rejected", reason or f"rejected by {approved_by}")
        finding.touch()
        return finding
    finding.add_to_timeline("approved", f"approved by {approved_by}: {reason or 'proceed'}")
    _finish_remediation(finding)
    return finding


# ---------------------------------------------------------------------------
# Security Test Lab — 9 safe, isolated scenarios ------------------------------
# ---------------------------------------------------------------------------

LAB_SCENARIOS: dict[str, dict[str, Any]] = {
    "app_error": {
        "title": "[Lab] demo-app availability error",
        "issue": "demo-app returns 5xx / unavailable after a bad config rollout.",
        "severity": Severity.MEDIUM,
        "layer": SecurityLayer.APPLICATION,
        "domain": "Availability",
        "affected_resource": "Deployment/demo-app",
        "root_cause": "bad config rollout leaves replicas unavailable.",
        "recommended_solution": "Restart the deployment to restore a clean rollout.",
        "recommended_action": "restart_deployment",
        "action_params": {"deployment": "demo-app", "namespace": "ai-observability-demo"},
    },
    "high_cpu": {
        "title": "[Lab] sustained high CPU on cpu-demo",
        "issue": "cpu-demo sustains >80% CPU; no autoscaling configured",
        "severity": Severity.MEDIUM,
        "layer": SecurityLayer.APPLICATION,
        "domain": "ResourceUsage",
        "affected_resource": "Deployment/cpu-demo",
        "root_cause": "workload spike crosses the CPU threshold for >5 minutes.",
        "recommended_solution": "Scale the deployment to spread load (auto-allowed, low risk).",
        "recommended_action": "scale_deployment",
        "action_params": {"deployment": "cpu-demo", "desired_replicas": 3, "namespace": "ai-observability-demo"},
    },
    "crashloop": {
        "title": "[Lab] CrashLoopBackOff on crash-demo",
        "issue": "crash-demo container exits immediately (code 1) and the pod is in CrashLoopBackOff.",
        "severity": Severity.HIGH,
        "layer": SecurityLayer.CONTAINER,
        "domain": "Stability",
        "affected_resource": "Deployment/crash-demo",
        "root_cause": "container image entrypoint exits when the config file is missing.",
        "recommended_solution": "Restart the deployment after validating the config; approval required.",
        "recommended_action": "restart_deployment",
        "action_params": {"deployment": "crash-demo", "namespace": "ai-observability-demo"},
    },
    "falco": {
        "title": "[Lab] Falco: terminal shell in container",
        "issue": "Falco flagged an interactive shell (+ sensitive-file read) inside test-pod.",
        "severity": Severity.HIGH,
        "layer": SecurityLayer.CONTAINER,
        "domain": "Falco",
        "affected_resource": "Pod/test-pod",
        "root_cause": "an admin opened a shell via kubectl exec into a running pod.",
        "recommended_solution": "Quarantine the pod by dropping privileges / rolling the workload; approval required.",
        "recommended_action": "apply_security_config",
        "action_params": {"config": "drop-privileged", "target": "test-pod", "namespace": "ai-observability-demo"},
    },
    "trivy": {
        "title": "[Lab] Trivy CVE in nginx:1.25",
        "issue": "Trivy scan reports known CVEs in the nginx:1.25 image used by demo-app.",
        "severity": Severity.HIGH,
        "layer": SecurityLayer.CONTAINER,
        "domain": "SCA",
        "affected_resource": "Deployment/demo-app (image nginx:1.25)",
        "root_cause": "outdated base image accumulates published vulnerabilities.",
        "recommended_solution": "Pin a patched image (tidy-image) and roll it out; approval required.",
        "recommended_action": "apply_security_config",
        "action_params": {"config": "tidy-image", "target": "demo-app", "namespace": "ai-observability-demo"},
    },
    "apparmor": {
        "title": "[Lab] AppArmor profile missing on crash-demo",
        "issue": "crash-demo containers run without an AppArmor containment profile.",
        "severity": Severity.MEDIUM,
        "layer": SecurityLayer.CONTAINER,
        "domain": "AppArmor",
        "affected_resource": "Pod/crash-demo",
        "root_cause": "container.appArmorProfile not set on the pod spec.",
        "recommended_solution": "Enable the demo AppArmor profile; approval required.",
        "recommended_action": "apply_security_config",
        "action_params": {"config": "enable-apparmor", "target": "crash-demo", "namespace": "ai-observability-demo"},
    },
    "privileged": {
        "title": "[Lab] privileged:true on injected pod",
        "issue": "a pod was admitted with privileged=true, defeating isolation.",
        "severity": Severity.CRITICAL,
        "layer": SecurityLayer.CONTAINER,
        "domain": "Privileged",
        "affected_resource": "Pod/lab-privileged",
        "root_cause": "PodSecurity admission allowed a privileged container (simulated).",
        "recommended_solution": "Drop the privileged flag; approval required.",
        "recommended_action": "apply_security_config",
        "action_params": {"config": "drop-privileged", "target": "lab-privileged", "namespace": "ai-observability-demo"},
    },
    "rbac": {
        "title": "[Lab] cluster-admin binding for ci-bot",
        "issue": "ci-bot ServiceAccount was bound to cluster-admin again.",
        "severity": Severity.CRITICAL,
        "layer": SecurityLayer.KUBERNETES_CLUSTER,
        "domain": "RBAC",
        "affected_resource": "ClusterRoleBinding/ci-bot-cluster-admin",
        "root_cause": "over-privileged binding created by a CI automation account.",
        "recommended_solution": "Roll back the over-privileged binding; approval required.",
        "recommended_action": "rollback_rbac",
        "action_params": {"binding_name": "ci-bot-cluster-admin"},
    },
    "netpol": {
        "title": "[Lab] no default-deny NetworkPolicy",
        "issue": "the demo namespace has no default-deny ingress/egress NetworkPolicy.",
        "severity": Severity.HIGH,
        "layer": SecurityLayer.KUBERNETES_CLUSTER,
        "domain": "NetworkPolicy",
        "affected_resource": "Namespace/ai-observability-demo",
        "root_cause": "no NetworkPolicy applied at namespace bootstrap.",
        "recommended_solution": "Apply the default-deny policy; approval required.",
        "recommended_action": "apply_security_config",
        "action_params": {"config": "default-deny-network-policy", "target": "ai-observability-demo", "namespace": "ai-observability-demo"},
    },
}


def lab_scenarios() -> list[dict[str, Any]]:
    return [
        {
            "key": key,
            "layer": SecurityLayer(S["layer"]).value if isinstance(S["layer"], SecurityLayer) else S["layer"],
            "title": S["title"],
            "decision_hint": "AUTO" if S["layer"] == SecurityLayer.APPLICATION else "APPROVAL_REQUIRED",
        }
        for key, S in LAB_SCENARIOS.items()
    ]


def run_lab(key: str) -> SecurityFinding:
    if key not in LAB_SCENARIOS:
        raise KeyError(f"unknown lab scenario {key!r}")
    spec = LAB_SCENARIOS[key]
    req = SecurityFindingRequest(
        title=spec["title"],
        issue=spec["issue"],
        severity=spec["severity"] if isinstance(spec["severity"], Severity) else Severity(spec["severity"]),
        layer=spec["layer"] if isinstance(spec["layer"], SecurityLayer) else SecurityLayer(spec["layer"]),
        domain=spec.get("domain", ""),
        affected_resource=spec.get("affected_resource", ""),
        root_cause=spec.get("root_cause", ""),
        recommended_solution=spec.get("recommended_solution", ""),
        recommended_action=spec.get("recommended_action", ""),
        action_params=spec.get("action_params", {}),
    )
    return create_finding(req, source=f"test-lab:{key}")